# Generated by Django 3.2.10 on 2023-03-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getActive', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tags',
            new_name='Tag',
        ),
    ]
