# Generated by Django 3.2.10 on 2023-03-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getActive', '0002_rename_tags_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='talk_date',
            new_name='activity_date',
        ),
    ]
