# Generated by Django 4.2.2 on 2023-07-02 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getActive', '0003_rename_talk_date_activity_activity_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
